name: Build and Deploy on AWS

on:
  push:
    branches:
      - main
      
jobs:
  build-deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
      #- uses: actions/checkout@v3
      #- uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn -B package --file **/pom.xml
      
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_SECRET_REGION }}
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name helloworld --s3-bucket teste-deploy-lambda-function-java --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_SECRET_REGION }} 
